# Build Geomini from designspace (Geomini-200.ufo, Geomini-800.ufo)
sources:
  - ufo/Geomini.designspace
  - ufo/Geomini-ExtraLight.ufo
  - ufo/Geomini-ExtraBold.ufo
familyName: "Geomini"

buildOTF: false

stat:
  Geomini[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800