# Build Geomini from designspace (Geomini-200.ufo, Geomini-800.ufo)
sources:
  - Geomini.designspace
  - Geomini-200.ufo
  - Geomini-800.ufo
familyName: "Geomini"

buildOTF: false

stat:
  Geomini[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Extra Light
      value: 200
    - name: Heavy
      value: 800