# Build Geomini from UFO source (Geomini-ExtraLight-2026-02-01-001959.ufo)
sources:
  - GeominiExtraLight.ufo
familyName: "Geomini"

buildOTF: false

stat:
  GeominiExtraLight.ttf:
  - name: Weight
    tag: wght
    values:
    - name: Extra Light
      value: 200
